# Generated by Django 5.0.1 on 2024-02-09 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=10)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_collab_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_collab_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollabSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField()),
                ('sender_status', models.CharField(blank=True, choices=[('attended', 'Attended'), ('absent', 'Absent')], max_length=20, null=True)),
                ('receiver_status', models.CharField(blank=True, choices=[('attended', 'Attended'), ('absent', 'Absent')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('collab_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_sessions', to='Skill.skillrequest')),
            ],
        ),
    ]
