# Generated by Django 5.0.1 on 2024-03-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skill', '0005_userskill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='category',
            field=models.CharField(choices=[('Art and Design', 'Art and Design'), ('Science and Technology', 'Science and Technology'), ('Culinary Arts', 'Culinary Arts'), ('Music and Performing Arts', 'Music and Performing Arts'), ('Language and Communication', 'Language and Communication'), ('Fitness and Wellness', 'Fitness and Wellness'), ('Craftsmanship', 'Craftsmanship'), ('Technology and IT', 'Technology and IT'), ('Sports and Recreation', 'Sports and Recreation'), ('History and Humanities', 'History and Humanities'), ('Parenting and Family', 'Parenting and Family'), ('Mindfulness and Well-being', 'Mindfulness and Well-being')], default='Art and Design', max_length=50),
        ),
    ]
