# Generated by Django 5.0.1 on 2024-03-07 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skill', '0006_alter_userskill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
