# Generated by Django 5.0.1 on 2024-03-12 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skill', '0008_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='category',
        ),
        migrations.AlterField(
            model_name='community',
            name='leader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='led_community', to=settings.AUTH_USER_MODEL),
        ),
    ]
