# Generated by Django 5.0.1 on 2024-03-15 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Skill', '0009_remove_community_category_alter_community_leader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Community',
        ),
    ]
