# Generated by Django 5.0.1 on 2024-03-16 06:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skill', '0013_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_chat_messages', to='Skill.community')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_community_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
