# Generated by Django 5.0.1 on 2024-03-16 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skill', '0015_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_time',
        ),
        migrations.AddField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
