# Generated by Django 5.0.1 on 2024-04-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skill', '0016_remove_event_date_time_event_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
