# Generated by Django 5.0.1 on 2024-04-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skill', '0017_review_sentiment_score_review_sentiment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='sentiment_score',
        ),
        migrations.RemoveField(
            model_name='review',
            name='sentiment_title',
        ),
        migrations.AddField(
            model_name='customuser',
            name='average_sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sentiment_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
