# Generated by Django 5.0.1 on 2024-04-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Skill', '0018_remove_review_sentiment_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='average_sentiment_score',
            new_name='sentiment_score',
        ),
    ]
