# Generated by Django 5.0.1 on 2024-04-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skill', '0019_rename_average_sentiment_score_customuser_sentiment_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='sentiment_score',
            new_name='average_sentiment_score',
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
