# Generated by Django 5.0.1 on 2024-04-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Skill', '0020_rename_sentiment_score_customuser_average_sentiment_score_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillPointsTransaction',
        ),
    ]
